# Generated by Django 5.2.7 on 2025-12-17 01:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Timestamp',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='todo',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
